spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:graphql
    username: sa
    password:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  graphql:
    graphiql:
      enabled: true
      printer:
        enabled: true